// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfn6dB7qVdR_DcBOL6ms98Pwzcp1RDcI',
    appId: '1:632068505817:ios:b8ca66368721ff4214fec8',
    messagingSenderId: '632068505817',
    projectId: 'library-mngmt-2026',
    storageBucket: 'library-mngmt-2026.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagementApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRfn6dB7qVdR_DcBOL6ms98Pwzcp1RDcI',
    appId: '1:632068505817:ios:b8ca66368721ff4214fec8',
    messagingSenderId: '632068505817',
    projectId: 'library-mngmt-2026',
    storageBucket: 'library-mngmt-2026.firebasestorage.app',
    iosBundleId: 'com.example.libraryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdawG0LAEeZw037nOmSMC-x9TR1M57jp8',
    appId: '1:632068505817:web:835e1c741d14842314fec8',
    messagingSenderId: '632068505817',
    projectId: 'library-mngmt-2026',
    authDomain: 'library-mngmt-2026.firebaseapp.com',
    storageBucket: 'library-mngmt-2026.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdawG0LAEeZw037nOmSMC-x9TR1M57jp8',
    appId: '1:632068505817:web:835e1c741d14842314fec8',
    messagingSenderId: '632068505817',
    projectId: 'library-mngmt-2026',
    authDomain: 'library-mngmt-2026.firebaseapp.com',
    storageBucket: 'library-mngmt-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDUm8yEi3jkXIElysOoTXfSDLeO-AQfsc',
    appId: '1:632068505817:android:3887f916a5544a4e14fec8',
    messagingSenderId: '632068505817',
    projectId: 'library-mngmt-2026',
    storageBucket: 'library-mngmt-2026.firebasestorage.app',
  );
}
